print("Olá turma do Python!")
print("Tudo bem!")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!")
idade: int = int(input("Qual é a sua idade? "))
print(f"Tu tens {idade} anos...")
cidade: str = input("Em qual cidade vives? ")
print(f"Tu vives em {cidade} uma cidade muito bonita! ")
irmaos: str = input ("Tens quantos irmaos?")
print(f"Tu tens {irmaos} ...")
cor: str = input("Qual a tua cor favotira? ")
print(f"Hmmm {cor} que cor bonita bonita! ")
escolha: str = input("Preferes Portatil ou Pc de mese? ")
print(f"Hmm {escolha} otima escolha ")
print(f"🤢 ")
print(f"🤫 ")
print(f"🥳 ")